### ISSUE TITLE
Support GraalVM 21.0

### ISSUE THREAD

**Issue by mike-neck** [mike-neck/graalvm-native-image-plugin#118]

**Comment by mike-neck** [comment]
```
Caused by: java.lang.IllegalArgumentException: cannot read version from /opt/hostedtoolcache/GraalVM/21.0.0-java8/x64/release
Please report the issue at https://github.com/mike-neck/graalvm-native-image-plugin/issues/new?template=bug_report.md .
	at org.mikeneck.graalvm.GraalVmVersion.findFromPath(GraalVmVersion.java:81)
	at org.mikeneck.graalvm.GraalVmHome.graalVmVersion(GraalVmHome.java:35)
	... 169 more
Caused by: java.lang.IllegalStateException: cannot found appropriate GraalVM version[java="1.8.0_282",graalvm="21.0.0",catalog="https://www.graalvm.org/component-catalog/v2/graal-updater-component-catalog-java8.properties|{ee=GraalVM Enterprise Edition}gds://oca.opensource.oracle.com/gds/meta-data.json"]
	at org.mikeneck.graalvm.GraalVmVersion.lambda$findFromMap$1(GraalVmVersion.java:107)
	at org.mikeneck.graalvm.GraalVmVersion.findFromMap(GraalVmVersion.java:104)
	at org.mikeneck.graalvm.GraalVmVersion.findFromReader(GraalVmVersion.java:96)
	at org.mikeneck.graalvm.GraalVmVersion.findFromPath(GraalVmVersion.java:72)
```
